---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 29966.
--- DateTime: 2024/11/3 10:15
---
if (redis.call('get',KEYS[1]==ARGV[1])) then
    return redis.call('del',KEYS[1])
end
return 0